ALTER TABLE memberships
    ADD COLUMN notified_7_days BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN notified_3_days BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN notified_1_day  BOOLEAN NOT NULL DEFAULT FALSE;